kind: pipeline
name: default

steps:
  - name: deploy Sakura
    image: appleboy/drone-scp:latest
    settings:
      host:
        from_secret: SSH_HOST
      user:
        from_secret: SSH_USER
      port:
        from_secret: SSH_PORT
      password:
        from_secret: SSH_PASSWD
      target: /opt/sakura/
      source:
        - ./*
    rm: true
    when:
      branch: [master]
      status: [success]

  - name: reload Sakura
    image: appleboy/drone-ssh:latest
    settings:
      host:
        from_secret: SSH_HOST
      user:
        from_secret: SSH_USER
      port:
        from_secret: SSH_PORT
      password:
        from_secret: SSH_PASSWD
      script:
        - pm2 restart all
