name: Sakura Auto Config Engine

on:
  push:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow
env:
  DOCKER_IMAGE_URL: qsomula/dashboard
  GITHUB_SHA: ${{ github.sha }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: [self-hosted, linux, ARM64]
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Build
    - name: Build Docker image
      run: |        
        docker build -t ${DOCKER_IMAGE_URL}:${GITHUB_SHA} .

    - name: Login Docker Hub Registry
      run: |
        docker login -u ${{ secrets.DOCKER_HOB_NAME }} -p ${{ secrets.DOCKER_HOB_PASSWORD }} ${DOCKER_IMAGE_URL}

    # Push the Docker image to Docker Hub
    - name: Publish
      run: |
        docker push ${DOCKER_IMAGE_URL}:${GITHUB_SHA}
